/* eslint-disable react/prop-types */
import { useContext, useEffect, useState } from "react";
import { CirclePlus } from "lucide-react";
import dayjs from "dayjs";
import useSWR from "swr";
import { AlertContext } from "../misc/AlertContext";
import ProductModal from "./ProductModal";
import FormProductEditor from "./FormProductEditor";
import DatePicker from "./DatePicker";
import fetcher from "../helpers/fetcher";

export default function FormEdit({ formData, close }) {
  const { addAlert } = useContext(AlertContext); const { data: publicForm } = useSWR(formData ? `/forms/public/${formData.id}` : null);
  const [products, setProducts] = useState([]); const [productModal, setProductModal] = useState(false); const [city, setCity] = useState(""); const [date, setDate] = useState(null); const [note, setNote] = useState(""); const [minimumOrderValue, setMinimumOrderValue] = useState(80); const [minimumEggQuantity, setMinimumEggQuantity] = useState(60); const [eggRequirement, setEggRequirement] = useState(false); const [submitting, setSubmitting] = useState(false);
  useEffect(() => { if (formData) { setProducts(formData.products || []); setCity(formData.city || ""); setDate(dayjs(formData.date, "DD-MM-YYYY")); setNote(formData.note || ""); setMinimumOrderValue(formData.minimumOrderValue ?? 80); setMinimumEggQuantity(formData.minimumEggQuantity ?? 60); setEggRequirement((formData.minimumEggQuantity ?? 0) > 0); } }, [formData]);
  const claimed = publicForm?.products?.flatMap((product) => (product.weightedItems || []).filter((item) => !item.available).map((item) => item.id)) || [];
  async function submit(event) { event.preventDefault(); setSubmitting(true); try { const response = await fetcher(`/forms/edit/${formData.id}`, "PUT", { id: formData.id, city, date: (date || dayjs()).format("DD-MM-YYYY"), note: note || null, products, minimumOrderValue: Number(minimumOrderValue), minimumEggQuantity: eggRequirement ? Number(minimumEggQuantity) : 0 }); addAlert("success", response); close(); window.location.reload(); } catch (error) { addAlert("error", error.message || error); } finally { setSubmitting(false); } }
  return <>{productModal && <ProductModal setProductModal={setProductModal} setProducts={setProducts} products={products} />}<form className="w-full min-h-screen bg-white p-4 rounded-lg flex flex-col gap-8 pb-12 tablet:!text-xl" onSubmit={submit}><section className="flex flex-col gap-3"><p>Oferta</p><button type="button" onClick={() => setProductModal(true)} className="flex gap-2 w-fit items-center"><CirclePlus color="#f28a72" /><span className="text-coral">Dodaj produkt</span></button>{products.map((product) => <FormProductEditor key={product.id} product={product} claimedItemIds={claimed} onChange={(next) => setProducts((current) => current.map((candidate) => candidate.id === next.id ? next : candidate))} onRemove={() => setProducts((current) => current.filter((candidate) => candidate.id !== product.id))} />)}</section><label className="flex flex-col gap-1">Miasto<input required value={city} onChange={(event) => setCity(event.target.value)} className="border p-2" /></label><label className="flex flex-col gap-1">Dodatkowe informacje<textarea value={note} onChange={(event) => setNote(event.target.value)} className="border p-2" /></label><DatePicker date={date} handleDateChange={setDate} /><label>Minimalna wartość zamówienia (PLN)<input required min="0" type="number" value={minimumOrderValue} onChange={(event) => setMinimumOrderValue(event.target.value)} className="ml-2 border p-1" /></label><label><input type="checkbox" checked={eggRequirement} onChange={(event) => setEggRequirement(event.target.checked)} /> Wymagaj minimum jajek</label>{eggRequirement && <label>Minimalna ilość jajek<input required min="1" type="number" value={minimumEggQuantity} onChange={(event) => setMinimumEggQuantity(event.target.value)} className="ml-2 border p-1" /></label>}<button disabled={submitting} className="self-center rounded-lg bg-coral p-4 text-xl disabled:bg-[#cccccc]">{submitting ? "Zapisywanie…" : "Edytuj formularz"}</button></form></>;
}
